name = "ConstantFunctions"
uuid = "cf45d141-e7cd-45e6-bffc-f815329abbc7"
authors = ["Olivier Verdier <olivier.verdier@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
